openapi: 3.0.1
info:
  title: PdfGenerator
  description: API Definition of PdfGenerator
  version: '1.0'
servers:
- url: http://localhost:8290/generate/pdf
paths:
  /card-id:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
